### ISSUE TITLE
error starting dev env, 

### ISSUE THREAD

**Issue by heidecke** [Solinea/goldstone-server#159] opened 2015-12-03 16:43 UTC
Ran `./bin/start_dev_env.sh` and noticed the following during startup:

This environment is from a fully new set of docker images, previous docker-machine was recreated.

```
gsappdev_1 | [2015-12-03 16:25:06,829: INFO/MainProcess] Task goldstone.core.tasks.update_persistent_graph[66bbf278-b338-4c9c-938e-01ed4204b857] succeeded in 18.996438316s: None
gsappdev_1 | Error: no such option: --prefix
gsappdev_1 | [2015-12-03 16:25:07,078: ERROR/MainProcess] Task goldstone.core.tasks.delete_indices[49e4f510-d6e9-4bd2-927f-1fc776736133] raised unexpected: CalledProcessError()
gsappdev_1 | Traceback (most recent call last):
gsappdev_1 |   File "/venv/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
gsappdev_1 |     R = retval = fun(*args, **kwargs)
gsappdev_1 |   File "/venv/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
gsappdev_1 |     return self.run(*args, **kwargs)
gsappdev_1 |   File "/home/app/goldstone/core/tasks.py", line 38, in delete_indices
gsappdev_1 |     return check_call(cmd.split())
gsappdev_1 |   File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
gsappdev_1 |     raise CalledProcessError(retcode, cmd)
gsappdev_1 | CalledProcessError
```

Seen in the same startup as #158.

**Comment by jxstanford** [comment] 2016-01-01 19:58
This appears to be originating from the call to curator.

**Comment by lexjacobs** [comment] 2016-01-19 18:41
Closing - Duplicate of #158

**Closed by lexjacobs** 2016-01-19 18:41 UTC
Labels: component: tasks, priority 2: high, type: bug
