### ISSUE TITLE
service status results consistent with expectations?

### ISSUE THREAD

**Issue by lexjacobs** [Solinea/goldstone-server#510] opened 2016-04-22 17:27 UTC
There are some new results showing up in services, perhaps related to canary?

<img width="308" alt="screen shot 2016-04-22 at 9 46 22 am" src="https://cloud.githubusercontent.com/assets/5633015/14749506/a5ca6e76-0874-11e6-955c-47a725bf7ce1.png">

http://localhost:8000/core/monitored_service/?ordering=state,name,host

![image](https://cloud.githubusercontent.com/assets/5633015/14749525/bacec1e6-0874-11e6-8c42-f241ebd031d8.png)

**Comment by jxstanford** [comment] 2016-04-22 17:30
this smells like a logstash pattern match mishap, but could also be related to #489

**Comment by jxstanford** [comment] 2016-05-17 15:21
I think I just addressed most of this by shutting of ceilometer (issue #536), and @vichargrave has been tightening up the searches on the back end.  I am not able to reproduce this issue, so am going to close it.  If you still see the problem, please reopen.

**Closed by jxstanford** 2016-05-17 15:21 UTC
Labels: priority 2: high, type: bug
